export const MOCK_REFERENCE_DATE = "2026-09-05";
export const WEEK_DAYS = [
    { nombre: "Lunes", corto: "Lun" },
    { nombre: "Martes", corto: "Mar" },
    { nombre: "Miércoles", corto: "Mié" },
    { nombre: "Jueves", corto: "Jue" },
    { nombre: "Viernes", corto: "Vie" },
    { nombre: "Sábado", corto: "Sáb" },
    { nombre: "Domingo", corto: "Dom" },
];

export const mockDoctors = [
    {
        id: 1,
        nombre: "Carlos García",
        especialidad: "Cardiología",
        departamento: "Huila",
        ciudad: "Agrado",
        direccion: "Calle 51 #45-32, consultorio 204",
        fotoPerfil: "/images/doctor3.jpg",
        disponibilidades: [
            { dia: "Lunes", bloques: [{ horaInicio: "08:00", horaFin: "12:00" }, { horaInicio: "14:00", horaFin: "18:00" }] },
            { dia: "Martes", bloques: [{ horaInicio: "09:00", horaFin: "13:00" }] },
            { dia: "Miércoles", bloques: [{ horaInicio: "08:00", horaFin: "12:00" }, { horaInicio: "15:00", horaFin: "17:00" }] },
            { dia: "Viernes", bloques: [{ horaInicio: "08:00", horaFin: "12:00" }] },
        ],
        horariosOcupados: ["2026-09-07T09:00", "2026-09-07T10:30", "2026-09-07T14:30"],
    },
    {
        id: 2,
        nombre: "Valentina Moreno",
        especialidad: "Pediatría",
        departamento: "Antioquia",
        ciudad: "Medellín",
        direccion: "Carrera 43A #16 Sur-47, torre médica",
        fotoPerfil: "/images/doctora1.jpg",
        disponibilidades: [
            { dia: "Lunes", bloques: [{ horaInicio: "07:30", horaFin: "11:30" }] },
            { dia: "Jueves", bloques: [{ horaInicio: "13:00", horaFin: "17:30" }] },
            { dia: "Sábado", bloques: [{ horaInicio: "09:00", horaFin: "13:00" }] },
        ],
        horariosOcupados: ["2026-09-05T10:30", "2026-09-07T08:30"],
    },
    {
        id: 3,
        nombre: "Sofía Herrera",
        especialidad: "Dermatología",
        departamento: "Cundinamarca",
        ciudad: "Bogotá",
        direccion: "Avenida Carrera 7 #119-14, piso 5",
        fotoPerfil: "/images/doctora2.png",
        disponibilidades: [
            { dia: "Martes", bloques: [{ horaInicio: "08:00", horaFin: "12:30" }] },
            { dia: "Miércoles", bloques: [{ horaInicio: "14:00", horaFin: "18:00" }] },
            { dia: "Domingo", bloques: [{ horaInicio: "08:00", horaFin: "11:00" }] },
        ],
        horariosOcupados: ["2026-09-06T09:00", "2026-09-08T10:00"],
    },
    {
        id: 4,
        nombre: "Andrés Ramírez",
        especialidad: "Medicina general",
        departamento: "Valle del Cauca",
        ciudad: "Cali",
        direccion: "Calle 5 #38-25, consultorio 310",
        fotoPerfil: "/images/foto_default.png",
        disponibilidades: [
            { dia: "Lunes", bloques: [{ horaInicio: "07:00", horaFin: "12:00" }, { horaInicio: "13:30", horaFin: "17:00" }] },
            { dia: "Miércoles", bloques: [{ horaInicio: "07:00", horaFin: "12:00" }] },
            { dia: "Viernes", bloques: [{ horaInicio: "07:00", horaFin: "15:00" }] },
        ],
        horariosOcupados: ["2026-09-07T07:30", "2026-09-07T14:00"],
    },
    {
        id: 5,
        nombre: "Laura Méndez",
        especialidad: "Ginecología",
        departamento: "Atlántico",
        ciudad: "Barranquilla",
        direccion: "Carrera 53 #80-67, consultorio 402",
        fotoPerfil: "/images/doctora1.jpg",
        disponibilidades: [
            { dia: "Martes", bloques: [{ horaInicio: "10:00", horaFin: "13:00" }, { horaInicio: "15:00", horaFin: "18:00" }] },
            { dia: "Jueves", bloques: [{ horaInicio: "08:00", horaFin: "12:00" }] },
        ],
        horariosOcupados: ["2026-09-08T10:30", "2026-09-08T16:00"],
    },
    {
        id: 6,
        nombre: "Julián Torres",
        especialidad: "Neurología",
        departamento: "Santander",
        ciudad: "Bucaramanga",
        direccion: "Carrera 33 #48-92, centro médico",
        fotoPerfil: "/images/doctor3.jpg",
        disponibilidades: [
            { dia: "Miércoles", bloques: [{ horaInicio: "08:30", horaFin: "12:30" }] },
            { dia: "Viernes", bloques: [{ horaInicio: "14:00", horaFin: "18:00" }] },
        ],
        horariosOcupados: ["2026-09-09T09:00", "2026-09-11T16:30"],
    },
    {
        id: 7,
        nombre: "Mariana López",
        especialidad: "Oftalmología",
        departamento: "Huila",
        ciudad: "Neiva",
        direccion: "Calle 12 #6-45, clínica central",
        fotoPerfil: "/images/doctora2.png",
        disponibilidades: [
            { dia: "Lunes", bloques: [{ horaInicio: "09:00", horaFin: "12:00" }] },
            { dia: "Jueves", bloques: [{ horaInicio: "09:00", horaFin: "12:00" }, { horaInicio: "14:00", horaFin: "16:30" }] },
            { dia: "Sábado", bloques: [{ horaInicio: "08:00", horaFin: "11:00" }] },
        ],
        horariosOcupados: ["2026-09-05T09:30", "2026-09-07T10:00"],
    },
    {
        id: 8,
        nombre: "Felipe Castro",
        especialidad: "Ortopedia",
        departamento: "Risaralda",
        ciudad: "Pereira",
        direccion: "Avenida Circunvalar #8-21, local 6",
        fotoPerfil: "/images/foto_default.png",
        disponibilidades: [],
        horariosOcupados: [],
    },
];
