"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv


# ──────────────────────────────────────────────────────────────────────────────
# CONFIGURACIÓN BASE
# ──────────────────────────────────────────────────────────────────────────────

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def env_bool(nombre, valor_predeterminado=False):
    return os.getenv(
        nombre,
        str(valor_predeterminado),
    ).strip().lower() in {
        "true",
        "1",
        "yes",
        "on",
    }


def env_list(nombre, valor_predeterminado=""):
    return [
        elemento.strip()
        for elemento in os.getenv(
            nombre,
            valor_predeterminado,
        ).split(",")
        if elemento.strip()
    ]


DEBUG = env_bool("DEBUG", True)

SECRET_KEY = os.environ["SECRET_KEY"]


# ──────────────────────────────────────────────────────────────────────────────
# HOSTS Y ORÍGENES
# ──────────────────────────────────────────────────────────────────────────────

ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    (
        "localhost,127.0.0.1"
        if DEBUG
        else "api.docsmart.site,doc-smart-production.up.railway.app"
    ),
)


if DEBUG:
    DEFAULT_HTTP_ORIGINS = (
        "http://localhost:3000,"
        "http://127.0.0.1:3000"
    )
else:
    DEFAULT_HTTP_ORIGINS = (
        "https://docsmart.site,"
        "https://www.docsmart.site,"
        "https://doc-smart-six.vercel.app"
    )


CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    DEFAULT_HTTP_ORIGINS,
)

CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    DEFAULT_HTTP_ORIGINS,
)

WEBSOCKET_ALLOWED_ORIGINS = env_list(
    "WEBSOCKET_ALLOWED_ORIGINS",
    DEFAULT_HTTP_ORIGINS,
)

CORS_ALLOW_CREDENTIALS = True


# ──────────────────────────────────────────────────────────────────────────────
# COOKIES
# ──────────────────────────────────────────────────────────────────────────────

AUTH_COOKIE_SECURE = not DEBUG
AUTH_COOKIE_SAMESITE = (
    "None"
    if not DEBUG
    else "Lax"
)

CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = (
    "None"
    if not DEBUG
    else "Lax"
)

SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = (
    "None"
    if not DEBUG
    else "Lax"
)


# ──────────────────────────────────────────────────────────────────────────────
# BYMAX
# ──────────────────────────────────────────────────────────────────────────────

BYMAX_DIAGNOSTICS_ENABLED = env_bool(
    "BYMAX_DIAGNOSTICS_ENABLED",
    False,
)

BYMAX_DIAGNOSTICS_COMMAND = os.getenv(
    "BYMAX_DIAGNOSTICS_COMMAND",
    "",
)

ELEVENLABS_API_KEY = os.getenv(
    "ELEVENLABS_API_KEY",
    "",
)

ELEVENLABS_VOICE_ID = os.getenv(
    "ELEVENLABS_VOICE_ID",
    "",
)

ELEVENLABS_MODEL_ID = os.getenv(
    "ELEVENLABS_MODEL_ID",
    "eleven_multilingual_v2",
)


# ──────────────────────────────────────────────────────────────────────────────
# APLICACIONES
# ──────────────────────────────────────────────────────────────────────────────

INSTALLED_APPS = [
    "daphne",

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "channels",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "django_extensions",

    "cloudinary",
    "cloudinary_storage",

    "users",
    "medicos",
    "catalogos",
    "citas",
    "chatbot",
    "historial_medico",
    "notificaciones",
    "storage_app",
]


# ──────────────────────────────────────────────────────────────────────────────
# MIDDLEWARE
# ──────────────────────────────────────────────────────────────────────────────

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # Debe estar antes de CommonMiddleware y CsrfViewMiddleware.
    "corsheaders.middleware.CorsMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ──────────────────────────────────────────────────────────────────────────────
# URLS, TEMPLATES Y ASGI
# ──────────────────────────────────────────────────────────────────────────────

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": (
            "django.template.backends.django."
            "DjangoTemplates"
        ),
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                (
                    "django.template.context_processors."
                    "request"
                ),
                (
                    "django.contrib.auth.context_processors."
                    "auth"
                ),
                (
                    "django.contrib.messages.context_processors."
                    "messages"
                ),
            ],
        },
    },
]

ASGI_APPLICATION = "core.asgi.application"


# ──────────────────────────────────────────────────────────────────────────────
# REDIS, CACHÉ Y CHANNELS
# ──────────────────────────────────────────────────────────────────────────────

REDIS_URL = os.getenv("REDIS_URL")

if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": (
                "django.core.cache.backends.redis."
                "RedisCache"
            ),
            "LOCATION": REDIS_URL,
            "KEY_PREFIX": "docsmart",
        },
    }

    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": (
                "channels_redis.core."
                "RedisChannelLayer"
            ),
            "CONFIG": {
                "hosts": [
                    REDIS_URL,
                ],
            },
        },
    }

else:
    CACHES = {
        "default": {
            "BACKEND": (
                "django.core.cache.backends.locmem."
                "LocMemCache"
            ),
            "LOCATION": "docsmart-development",
        },
    }

    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": (
                "channels.layers."
                "InMemoryChannelLayer"
            ),
        },
    }


# ──────────────────────────────────────────────────────────────────────────────
# BASE DE DATOS
# ──────────────────────────────────────────────────────────────────────────────

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ["DB_NAME"],
        "USER": os.environ["DB_USER"],
        "PASSWORD": os.environ["DB_PASSWORD"],
        "HOST": os.environ["DB_HOST"],
        "PORT": os.environ.get(
            "DB_PORT",
            "3306",
        ),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    },
}


# ──────────────────────────────────────────────────────────────────────────────
# DJANGO REST FRAMEWORK
# ──────────────────────────────────────────────────────────────────────────────

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "utils.CustomJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        (
            "rest_framework.permissions."
            "IsAuthenticated"
        ),
    ],
    "DEFAULT_THROTTLE_RATES": {
        "bymax_voice": "30/min",
        "bymax_chat": "30/min",
        "bymax_diagnostics": "10/min",
        "historial_read": "60/min",
        "historial_write": "10/min",
    },
}


# ──────────────────────────────────────────────────────────────────────────────
# JWT
# ──────────────────────────────────────────────────────────────────────────────

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=30,
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=7,
    ),
}


# ──────────────────────────────────────────────────────────────────────────────
# CONTRASEÑAS
# ──────────────────────────────────────────────────────────────────────────────

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ──────────────────────────────────────────────────────────────────────────────
# EMAIL
# ──────────────────────────────────────────────────────────────────────────────

EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
)

EMAIL_HOST = os.getenv(
    "EMAIL_HOST",
    "smtp.gmail.com",
)

EMAIL_PORT = int(
    os.getenv(
        "EMAIL_PORT",
        "587",
    )
)

EMAIL_HOST_USER = os.getenv(
    "EMAIL_HOST_USER",
)

EMAIL_HOST_PASSWORD = os.getenv(
    "EMAIL_HOST_PASSWORD",
)

EMAIL_USE_TLS = env_bool(
    "EMAIL_USE_TLS",
    True,
)

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# ──────────────────────────────────────────────────────────────────────────────
# CLOUDINARY
# ──────────────────────────────────────────────────────────────────────────────

CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.getenv(
        "CLOUDINARY_CLOUD_NAME",
    ),
    "API_KEY": os.getenv(
        "CLOUDINARY_API_KEY",
    ),
    "API_SECRET": os.getenv(
        "CLOUDINARY_API_SECRET",
    ),
}


# ──────────────────────────────────────────────────────────────────────────────
# OBJECT STORAGE DE RAILWAY
# ──────────────────────────────────────────────────────────────────────────────

AWS_ACCESS_KEY_ID = os.getenv(
    "AWS_ACCESS_KEY_ID",
)

AWS_SECRET_ACCESS_KEY = os.getenv(
    "AWS_SECRET_ACCESS_KEY",
)

AWS_S3_ENDPOINT_URL = os.getenv(
    "AWS_STORAGE_ENDPOINT_URL",
)

AWS_S3_REGION_NAME = os.getenv(
    "AWS_S3_REGION_NAME",
)

AWS_STORAGE_BUCKET_NAME = os.getenv(
    "AWS_STORAGE_BUCKET_NAME",
)


STORAGES = {
    # Cloudinary continúa almacenando las fotos de perfil.
    "default": {
        "BACKEND": (
            "cloudinary_storage.storage."
            "MediaCloudinaryStorage"
        ),
    },

    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage."
            "StaticFilesStorage"
        ),
    },

    # Storage específico para archivos generales.
    "railway": {
        "BACKEND": (
            "storages.backends.s3.S3Storage"
        ),
        "OPTIONS": {
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "bucket_name": (
                AWS_STORAGE_BUCKET_NAME
            ),
            "endpoint_url": AWS_S3_ENDPOINT_URL,
            "region_name": AWS_S3_REGION_NAME,
            "default_acl": None,
            "querystring_auth": True,
            "file_overwrite": False,
        },
    },
}


# ──────────────────────────────────────────────────────────────────────────────
# INTERNACIONALIZACIÓN
# ──────────────────────────────────────────────────────────────────────────────

LANGUAGE_CODE = "es"

TIME_ZONE = "America/Bogota"

USE_I18N = True
USE_TZ = True


# ──────────────────────────────────────────────────────────────────────────────
# ARCHIVOS ESTÁTICOS
# ──────────────────────────────────────────────────────────────────────────────

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"