# Generated by Django 4.2 on 2026-05-10 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_ciudad_departamento_delete_lugar_ciudad_departamento'),
        ('medicos', '0003_medico_ultimo_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.ciudad'),
        ),
        migrations.AddField(
            model_name='medico',
            name='direccion',
            field=models.CharField(default='calle 51 #45 -32', max_length=255),
            preserve_default=False,
        ),
    ]
