# Generated by Django 4.2 on 2026-05-17 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0004_medico_ciudad_medico_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='ciudad',
            new_name='id_ciudad',
        ),
    ]
