# Generated by Django 4.2 on 2026-05-17 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_ciudad_api_id_departamento_api_id'),
        ('medicos', '0005_rename_ciudad_medico_id_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='id_ciudad',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='catalogos.ciudad'),
            preserve_default=False,
        ),
    ]
