# Generated by Django 4.2 on 2026-05-24 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_ciudad_api_id_departamento_api_id'),
        ('medicos', '0006_alter_medico_id_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='id_ciudad',
        ),
        migrations.AddField(
            model_name='medico',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.ciudad'),
        ),
    ]
