# Generated by Django 4.2 on 2026-08-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0007_remove_medico_id_ciudad_medico_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/medicos/'),
        ),
    ]
