# Generated by Django 5.2.17 on 2026-09-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0008_medico_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='estado_validacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='medico',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
