# Generated by Django 5.2.17 on 2026-09-11 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0009_medico_estado_validacion_medico_fecha_validacion_and_more'),
        ('storage_app', '0003_archivo_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='estado_validacion',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='fecha_validacion',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='motivo_rechazo',
        ),
        migrations.CreateModel(
            name='SolicitudValidacionMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('puede_reintentar_desde', models.DateTimeField(blank=True, null=True)),
                ('hoja_vida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_medicas', to='storage_app.archivo')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_validacion', to='medicos.medico')),
            ],
        ),
    ]
