# Generated by Django 5.2.17 on 2026-09-21 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0011_disponibilidadmedico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcepcionDisponibilidadMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('NO_DISPONIBLE', 'No disponible'), ('HORARIO_ESPECIAL', 'Horario especial')], max_length=20)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones_disponibilidad', to='medicos.medico')),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
    ]
