# Generated by Django 5.2.17 on 2026-09-21 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0012_excepciondisponibilidadmedico'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='duracion_consulta',
            field=models.PositiveSmallIntegerField(default=30, help_text='Duración de la consulta en minutos', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
