# Generated by Django 5.2.17 on 2026-10-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0013_medico_duracion_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='correo_verificado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='documento_verificado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('PASAPORTE', 'Pasaporte'), ('RC', 'Registro civil')], default='CC', max_length=20),
        ),
        migrations.AlterField(
            model_name='medico',
            name='cedula',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
