# Generated by Django 4.2 on 2026-04-30 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_ultimo_envio'),
        ('citas', '0001_initial'),
        ('catalogos', '0002_estado_lugar_medio'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico_general', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo_consulta', models.TextField()),
                ('cedula', models.CharField(max_length=20)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.cita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
        ),
    ]
