# Generated by Django 4.2 on 2026-05-02 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_historialclinico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialClinico',
        ),
    ]
