# Generated by Django 4.2 on 2026-05-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_ciudad_departamento_delete_lugar_ciudad_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='api_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='api_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
