from pathlib import Path
p=Path('frontend/scripts/verify-design-corrections.cjs');s=p.read_text(encoding='utf-8').replace("await page.emulateMedia({colorScheme:'light'});assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'light');", "await page.emulateMedia({colorScheme:'light'});await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');")
s=s.replace("    if(url.pathname.endsWith('/usuarios/registro/'))", "    if(url.pathname.endsWith('/perfil/admin/'))return json({ok:true,data:{id:44,rol:'admin',nombre:'Cuenta de prueba'}});\n    if(url.pathname.endsWith('/medicos/especialidades/'))return json({ok:true,data:[{id:1,nombre:'Medicina general'}]});\n    if(url.pathname.endsWith('/catalogos/departamentos/'))return json({ok:true,data:[{id:1,nombre:'Bogotá'}]});\n    if(url.pathname.endsWith('/departamentos/1/ciudades/'))return json({ok:true,data:[{id_ciudad:1,nombre_ciudad:'Bogotá'}]});\n    if(url.pathname.endsWith('/usuarios/registro/'))")
s=s.replace("  await page.emulateMedia({reducedMotion", '''  await go('/register?role=medico');
  for(const [name,value]of Object.entries({nombre:'Cuenta',apellido:'Prueba',cedula:'123456789',fecha_nacimiento:'1990-01-01'}))await page.locator(`input[name="${name}"]`).fill(value);
  await page.getByRole('button',{name:'Siguiente',exact:true}).click();await page.locator('input[name="telefono"]').fill('3001234567');await page.locator('input[name="direccion"]').fill('Consultorio de prueba');await page.locator('select[name="departamento_filtro"]').selectOption('1');await page.locator('select[name="id_ciudad"]').selectOption('1');await page.locator('select[name="id_especialidad"]').selectOption('1');await page.getByRole('button',{name:'Siguiente',exact:true}).click();
  await page.locator('input[name="correo"]').fill('doctor-fixture@example.com');await page.locator('input[name="contraseña"]').fill('ClavePrueba123');await page.locator('input[name="confirmar_contraseña"]').fill('ClavePrueba123');await page.locator('#hoja-vida').setInputFiles({name:'fixture.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 browser test fixture')});await page.getByRole('button',{name:'Registrarse',exact:true}).click();await page.getByRole('heading',{name:'¡Solicitud enviada!'}).waitFor();await shot('doctor-registration-completed');await page.getByRole('button',{name:'Aceptar',exact:true}).click();await page.waitForURL('**/login');
  assert.equal(requests['/api/medicos/registro/'],1);assert.equal(requests['/api/login/'],2);
  await page.emulateMedia({reducedMotion''')
s=s.replace("await page.getByRole('button',{name:'Verificar y continuar',exact:true}).click();await page.getByText('Documento ilegible.'", "await page.evaluate(()=>{document.querySelector('form').requestSubmit();document.querySelector('form').requestSubmit()});await page.getByRole('status').filter({hasText:'Verificando tu documento'}).waitFor();await shot('document-pending');await page.getByText('Documento ilegible.'",1)
s=s.replace("  otpMode='false';", "  await page.getByRole('button',{name:'Reenviar código',exact:true}).click();await page.getByText('Código reenviado.',{exact:false}).waitFor();assert.equal(await page.locator('input[name=\"otp\"]').inputValue(),'123456');\n  otpMode='false';")
p.write_text(s,encoding='utf-8',newline='\n')
# Extend visual/contrast audit to public and admin dashboard with its existing empty states.
p=Path('frontend/scripts/verify-contrast.cjs');s=p.read_text(encoding='utf-8').replace("    if(url.pathname.endsWith('/usuarios/registro/'))", "    if(url.pathname.endsWith('/perfil/admin/'))return json({ok:true,data:{id:44,rol:'admin',nombre:'Cuenta de prueba'}});\n    if(url.pathname.endsWith('/usuarios/registro/'))").replace("'/doctor/dashboard']", "'/doctor/dashboard','/admin/dashboard','/']").replace("if(url.includes('dashboard'))await", "if(url==='/doctor/dashboard')await");p.write_text(s,encoding='utf-8',newline='\n')
# Repair decorative rule comment encoding, no semantic code changes.
p=Path('frontend/components/forms/registerForm/RegisterForm.js');s=p.read_text(encoding='utf-8').replace('â”€','─');p.write_text(s,encoding='utf-8',newline='\n')
