from pathlib import Path
p=Path('frontend/src/app/globals.css');s=p.read_text(encoding='utf-8')+'\n.swal2-popup{border:1px solid var(--border)!important;border-radius:24px!important;box-shadow:var(--shadow)!important}.swal2-confirm{min-height:44px;background:var(--brand-solid)!important;color:var(--on-accent)!important;border-radius:10px!important;font-weight:600!important}.swal2-confirm:hover{background:#2445b4!important}.swal2-cancel{min-height:44px;background:var(--surface-muted)!important;color:var(--text-primary)!important;border:1px solid var(--control-border)!important;border-radius:10px!important}\n';p.write_text(s,encoding='utf-8',newline='\n')
p=Path('frontend/components/forms/loginForm/useLogin.js');s=p.read_text(encoding='utf-8').replace('title: data.message,','title: data.message || "Sesión iniciada",').replace('Bienvenido de nuevo ${data.data.nombre} ${data.data.apellido}, a ingresado como ${data.data.rol}','Bienvenido de nuevo, ${data.data.nombre} ${data.data.apellido}.');p.write_text(s,encoding='utf-8',newline='\n')
p=Path('frontend/components/forms/registerForm/RegisterForm.js');s=p.read_text(encoding='utf-8');s=s.replace("                {role === 'paciente' && <p className={styles.stepTitle}>","                {role === 'medico' && <p className={styles.stepTitle}>Paso {step} de 3 · {['Datos personales', 'Ubicación y especialidad', 'Credenciales y hoja de vida'][step - 1]}</p>}\n                {role === 'paciente' && <p className={styles.stepTitle}>")
lines=[]
for line in s.splitlines():
 if '<Input' in line and 'readOnly=' not in line:line=line.replace('<Input ','<Input readOnly={loading} ',1)
 if '<Button' in line and 'disabled=' not in line:line=line.replace('<Button ','<Button disabled={loading} ',1)
 lines.append(line)
s='\n'.join(lines)+'\n';s=s.replace('disabled={!form.departamento_filtro}','disabled={loading || !form.departamento_filtro}').replace('aria-label="Departamento" name=','disabled={loading} aria-label="Departamento" name=').replace('aria-label="Especialidad" name=','disabled={loading} aria-label="Especialidad" name=');p.write_text(s,encoding='utf-8',newline='\n')
# Reuse full API fixtures and auth checks, skip already-passed viewport matrix for a final focused pass.
s=Path('frontend/scripts/verify-design-corrections.cjs').read_text(encoding='utf-8');a=s.index('  for(const width of [1440');b=s.index('  for(const [flowTheme',a);s=s[:a]+s[b:];s=s.replace("path.resolve(__dirname, '../../.impeccable/corrections')","path.resolve(process.cwd(), '.impeccable/corrections')");Path('.impeccable/verify-auth-final.cjs').write_text(s,encoding='utf-8',newline='\n')
