# Generated by Django 4.2 on 2026-05-07 00:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_cita_id_estado_alter_cita_id_lugar_and_more'),
        ('users', '0003_usuario_ultimo_envio'),
        ('medicos', '0003_medico_ultimo_envio'),
        ('historial_medico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialclinico',
            name='cedula',
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='historiales', to='medicos.medico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.cita'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales', to='users.usuario'),
        ),
    ]
