# Generated by Django 4.2 on 2026-08-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='storage_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
