# Generated by Django 5.2.17 on 2026-09-10 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0009_medico_estado_validacion_medico_fecha_validacion_and_more'),
        ('storage_app', '0002_alter_archivo_storage_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='medicos.medico'),
        ),
    ]
