// MOCKUP TEMPORAL: eliminar este archivo cuando la página consuma la API real.
// Estos registros son ficticios y existen únicamente para validar la interfaz.
export const MOCK_DOCTOR_REQUESTS = [
    {
        id: 1,
        nombre_completo: "Carlos Martínez",
        cedula: "1023456789",
        especialidad: "Cardiología",
        departamento: "Antioquia",
        ciudad: "Medellín",
        fecha_solicitud: "08/09/2026",
        estado_validacion: "pendiente",
        fecha_nacimiento: "14/02/1984",
        telefono: "300 000 0001",
        correo: "carlos.martinez@ejemplo.test",
        direccion: "Calle 10 # 24-35",
    },
    {
        id: 2,
        nombre_completo: "Laura Fernández",
        cedula: "1098765432",
        especialidad: "Dermatología",
        departamento: "Cundinamarca",
        ciudad: "Bogotá",
        fecha_solicitud: "07/09/2026",
        estado_validacion: "aprobado",
        fecha_nacimiento: "23/06/1988",
        telefono: "300 000 0002",
        correo: "laura.fernandez@ejemplo.test",
        direccion: "Carrera 18 # 72-40",
    },
    {
        id: 3,
        nombre_completo: "Sebastián Rodríguez",
        cedula: "1002345678",
        especialidad: "Medicina General",
        departamento: "Valle del Cauca",
        ciudad: "Cali",
        fecha_solicitud: "05/09/2026",
        estado_validacion: "rechazado",
        fecha_nacimiento: "09/11/1982",
        telefono: "300 000 0003",
        correo: "sebastian.rodriguez@ejemplo.test",
        direccion: "Avenida 6N # 31-18",
    },
];
