# Generated by Django 4.2 on 2026-08-02 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_usuario_ultimo_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nuevo chat', max_length=150)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('archivado', 'Archivado'), ('eliminado', 'Eliminado')], default='activo', max_length=20)),
                ('estado_conversacion', models.CharField(default='normal', max_length=100)),
                ('contexto_temporal', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ultima_interaccion', models.DateTimeField(auto_now=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='users.usuario')),
            ],
            options={
                'ordering': ['-ultima_interaccion'],
            },
        ),
        migrations.CreateModel(
            name='ToolLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tool', models.CharField(max_length=100)),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('respuesta', models.JSONField(blank=True, null=True)),
                ('correcto', models.BooleanField(default=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('tokens', models.PositiveIntegerField(default=0)),
                ('latencia', models.FloatField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chatbot_tool_log',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SesionBymax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='activo', max_length=50)),
                ('escala_animo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('voz_activada', models.BooleanField(default=False)),
                ('despertador_activo', models.BooleanField(default=False)),
                ('idioma', models.CharField(default='es', max_length=10)),
                ('contexto_acumulado', models.TextField(blank=True, default='')),
                ('ultima_conversacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sesion_bymax', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chatbot_sesion_bymax',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('es_bot', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('voz', 'Voz'), ('imagen', 'Imagen'), ('archivo', 'Archivo'), ('sistema', 'Sistema')], default='texto', max_length=20)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('tool_ejecutada', models.CharField(blank=True, max_length=100, null=True)),
                ('tokens', models.PositiveIntegerField(default=0)),
                ('tiempo_respuesta', models.FloatField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chatbot.chat')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
