# Generated by Django 4.2 on 2026-08-02 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_ultimo_envio'),
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionbymax',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sesion_bymax', to='users.usuario'),
        ),
        migrations.AlterField(
            model_name='toollog',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_logs', to='users.usuario'),
        ),
    ]
