# Generated by Django 5.2.17 on 2026-09-07 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_redactar_payloads_toollog'),
        ('storage_app', '0002_alter_archivo_storage_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='archivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_chatbot', to='storage_app.archivo'),
        ),
    ]
