# Generated by Django 5.2.17 on 2026-09-07 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_mensaje_archivo'),
        ('medicos', '0008_medico_foto_perfil'),
        ('users', '0004_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='id_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats_bymax', to='medicos.medico'),
        ),
        migrations.AddField(
            model_name='toollog',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_logs_bymax', to='medicos.medico'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='users.usuario'),
        ),
        migrations.AlterField(
            model_name='toollog',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_logs', to='users.usuario'),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('id_medico__isnull', True), ('id_usuario__isnull', False)), models.Q(('id_medico__isnull', False), ('id_usuario__isnull', True)), _connector='OR'), name='chat_un_solo_propietario'),
        ),
        migrations.AddConstraint(
            model_name='toollog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('medico__isnull', True), ('usuario__isnull', False)), models.Q(('medico__isnull', False), ('usuario__isnull', True)), _connector='OR'), name='toollog_un_solo_actor'),
        ),
    ]
