# Generated by Django 5.2.17 on 2026-09-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_propietarios_medicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='contexto_clinico',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
