# Generated by Django 5.2.17 on 2026-09-07 20:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chatbot', '0006_contexto_clinico_mensajes'),
        ('medicos', '0008_medico_foto_perfil'),
        ('users', '0004_usuario_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorBymax',
            fields=[
                ('correlacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=60)),
                ('operacion', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chat')),
            ],
        ),
        migrations.CreateModel(
            name='SesionDiagnostico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sesion_hash', models.CharField(max_length=64)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
            options={
                'permissions': [('view_diagnostics', 'Consultar diagnóstico sanitizado de Bymax')],
            },
        ),
        migrations.CreateModel(
            name='EstadoAnimoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('puntuacion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('preguntado_en', models.DateTimeField(auto_now_add=True)),
                ('respondido_en', models.DateTimeField(blank=True, null=True)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicos.medico')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'fecha'), name='animo_usuario_dia'), models.UniqueConstraint(fields=('medico', 'fecha'), name='animo_medico_dia'), models.CheckConstraint(condition=models.Q(models.Q(('medico__isnull', True), ('rol', 'paciente'), ('usuario__isnull', False)), models.Q(('medico__isnull', False), ('rol', 'medico'), ('usuario__isnull', True)), _connector='OR'), name='animo_actor_rol'), models.CheckConstraint(condition=models.Q(('puntuacion__isnull', True), models.Q(('puntuacion__gte', 1), ('puntuacion__lte', 10)), _connector='OR'), name='animo_escala')],
            },
        ),
        migrations.CreateModel(
            name='PermisoDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'permiso'), name='permiso_diagnostico_unico')],
            },
        ),
        migrations.CreateModel(
            name='TurnoBymax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.UUIDField()),
                ('huella', models.CharField(max_length=64)),
                ('estado', models.CharField(default='procesando', max_length=15)),
                ('respuesta', models.JSONField(default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chat')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('chat', 'clave'), name='turno_bymax_unico')],
            },
        ),
    ]
