# Generated by Django 5.2.17 on 2026-09-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_errorbymax_sesiondiagnostico_estadoanimodiario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='resultado',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
