# Generated by Django 4.2 on 2026-07-25 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0007_remove_medico_id_ciudad_medico_ciudad'),
        ('users', '0003_usuario_ultimo_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('cita_confirmada', 'Cita confirmada'), ('cita_cancelada', 'Cita cancelada'), ('cita_agendada', 'Cita agendada'), ('historial_creado', 'Historial creado'), ('mensaje_nuevo', 'Mensaje nuevo')], max_length=50)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicos.medico')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
