# Generated by Django 5.2.17 on 2026-09-29 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0006_cita_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_habilitacion_anticipada', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conversacion', to='citas.cita')),
            ],
        ),
    ]
