# Generated by Django 5.2.17 on 2026-09-30 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_citas', '0001_initial'),
        ('medicos', '0013_medico_duracion_consulta'),
        ('storage_app', '0003_archivo_medico'),
        ('users', '0005_usuario_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('paciente', 'paciente'), ('medico', 'medico'), ('nota_previa', 'nota_previa'), ('sistema', 'sistema')], max_length=16)),
                ('contenido', models.TextField(blank=True, max_length=4000)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('client_message_id', models.UUIDField(blank=True, null=True)),
                ('clave_evento', models.CharField(blank=True, max_length=120, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('cupo_nota', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes', to='chat_citas.conversacion')),
                ('emisor_medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='medicos.medico')),
                ('emisor_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AdjuntoConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='adjunto_chat', to='storage_app.archivo')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos', to='chat_citas.conversacion')),
                ('mensaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos', to='chat_citas.mensaje')),
            ],
        ),
        migrations.AddField(
            model_name='conversacion',
            name='ultimo_leido_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='chat_citas.mensaje'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='ultimo_leido_paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='chat_citas.mensaje'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['conversacion', 'id'], name='chat_historial_idx'),
        ),
        migrations.AddConstraint(
            model_name='mensaje',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('clave_evento__isnull', True), ('client_message_id__isnull', False), ('emisor_medico__isnull', True), ('emisor_usuario__isnull', False), ('tipo__in', ['paciente', 'nota_previa'])), models.Q(('clave_evento__isnull', True), ('client_message_id__isnull', False), ('emisor_medico__isnull', False), ('emisor_usuario__isnull', True), ('tipo', 'medico')), models.Q(('clave_evento__isnull', False), ('client_message_id__isnull', True), ('emisor_medico__isnull', True), ('emisor_usuario__isnull', True), ('tipo', 'sistema')), _connector='OR'), name='chat_emisor_valido'),
        ),
        migrations.AddConstraint(
            model_name='mensaje',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cupo_nota', 1), ('cupo_nota__isnull', False), ('tipo', 'nota_previa')), models.Q(models.Q(('tipo', 'nota_previa'), _negated=True), ('cupo_nota__isnull', True)), _connector='OR'), name='chat_slot_nota_valido'),
        ),
        migrations.AddConstraint(
            model_name='mensaje',
            constraint=models.UniqueConstraint(fields=('conversacion', 'emisor_usuario', 'client_message_id'), name='chat_uuid_usuario'),
        ),
        migrations.AddConstraint(
            model_name='mensaje',
            constraint=models.UniqueConstraint(fields=('conversacion', 'emisor_medico', 'client_message_id'), name='chat_uuid_medico'),
        ),
        migrations.AddConstraint(
            model_name='mensaje',
            constraint=models.UniqueConstraint(fields=('conversacion', 'clave_evento'), name='chat_evento_unico'),
        ),
        migrations.AddConstraint(
            model_name='mensaje',
            constraint=models.UniqueConstraint(fields=('conversacion', 'cupo_nota'), name='chat_nota_unica'),
        ),
    ]
