# Generated by Django 4.2 on 2026-05-02 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_ultimo_envio'),
        ('medicos', '0003_medico_ultimo_envio'),
        ('catalogos', '0004_delete_historialclinico'),
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='creada_en',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cita',
            name='id_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.estado'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.lugar'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicos.medico'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
        ),
        migrations.CreateModel(
            name='RecordatorioCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_envio_recordatorio', models.DateTimeField()),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.cita')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.estado')),
                ('id_medios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.medio')),
            ],
        ),
    ]
