# Generated by Django 4.2 on 2026-05-07 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_medico_ultimo_envio'),
        ('users', '0003_usuario_ultimo_envio'),
        ('catalogos', '0004_delete_historialclinico'),
        ('citas', '0002_remove_cita_creada_en_remove_cita_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='id_estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalogos.estado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='id_lugar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalogos.lugar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='id_medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='medicos.medico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.usuario'),
            preserve_default=False,
        ),
    ]
