# Generated by Django 4.2 on 2026-05-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_cita_id_estado_alter_cita_id_lugar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='id_lugar',
        ),
    ]
