# Generated by Django 4.2 on 2026-08-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_remove_cita_id_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
