# Generated by Django 5.2.17 on 2026-09-21 22:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_cita_fecha_cancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
