# Generated by Django 5.2.17 on 2026-10-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_cita_fecha_inasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='codigo_cita',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True, unique=True),
        ),
    ]
