# Generated by Django 5.2.17 on 2026-10-08 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_cita_fecha_inasistencia'),
        ('storage_app', '0003_archivo_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_limite_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_recordatorio_cierre_24h',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_recordatorio_cierre_48h',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DocumentoSeguimientoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='documento_seguimiento_cita', to='storage_app.archivo')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_seguimiento', to='citas.cita')),
            ],
        ),
    ]
