# Generated by Django 5.2.17 on 2026-10-09 02:18

import citas.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_cita_codigo_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='codigo_cita',
            field=models.CharField(default=citas.utils.generarCodigoCita, editable=False, max_length=12, unique=True),
        ),
    ]
