# Generated by Django 5.2.17 on 2026-10-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_alter_cita_codigo_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='motivo_consulta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
