# Generated by Django 5.2.17 on 2026-10-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0010_cita_motivo_consulta'),
        ('citas', '0011_cita_fecha_completada'),
    ]

    operations = [
    ]
