# Generated by Django 4.2 on 2026-04-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_token_reset_usuario_token_reset_expira'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultimo_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
