# Generated by Django 5.2.17 on 2026-09-28 07:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0003_archivo_medico'),
        ('users', '0005_usuario_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioCorreoUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nuevo_correo', models.EmailField(max_length=254)),
                ('otp_hash', models.CharField(max_length=255)),
                ('otp_expira_en', models.DateTimeField()),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('reenvios', models.PositiveSmallIntegerField(default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('bloqueado', 'Bloqueado'), ('expirado', 'Expirado')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_correo', to='users.usuario')),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'estado'], name='users_cambi_usuario_37bf72_idx'), models.Index(fields=['nuevo_correo', 'estado'], name='users_cambi_nuevo_c_2307be_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcesoRegistroUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_declarado', models.CharField(max_length=100)),
                ('apellido_declarado', models.CharField(max_length=100)),
                ('fecha_nacimiento_declarada', models.DateField()),
                ('cedula_declarada', models.CharField(max_length=20)),
                ('correo', models.EmailField(db_index=True, max_length=254)),
                ('contraseña_hash', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('estatura', models.FloatField()),
                ('peso', models.FloatField()),
                ('correo_verificado', models.BooleanField(default=False)),
                ('correo_verificado_en', models.DateTimeField(blank=True, null=True)),
                ('otp_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('otp_expira_en', models.DateTimeField(blank=True, null=True)),
                ('intentos_otp', models.PositiveSmallIntegerField(default=0)),
                ('reenvios_otp', models.PositiveSmallIntegerField(default=0)),
                ('ultimo_envio_otp', models.DateTimeField(blank=True, null=True)),
                ('documento_verificado', models.BooleanField(default=False)),
                ('documento_verificado_en', models.DateTimeField(blank=True, null=True)),
                ('intentos_documento', models.PositiveSmallIntegerField(default=0)),
                ('cedula_verificada', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_verificado', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_verificado', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento_verificada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('iniciado', 'Iniciado'), ('correo_verificado', 'Correo verificado'), ('documento_cargado', 'Documento cargado'), ('documento_verificado', 'Documento verificado'), ('completado', 'Completado'), ('bloqueado', 'Bloqueado'), ('expirado', 'Expirado')], default='iniciado', max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('expira_en', models.DateTimeField()),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_registro_usuario', to='storage_app.archivo')),
            ],
            options={
                'indexes': [models.Index(fields=['correo', 'estado'], name='users_proce_correo_26b4f4_idx'), models.Index(fields=['cedula_declarada', 'estado'], name='users_proce_cedula__025474_idx'), models.Index(fields=['estado', 'expira_en'], name='users_proce_estado_8ea89f_idx')],
            },
        ),
    ]
