# Generated by Django 5.2.17 on 2026-09-29 03:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_cambiocorreousuario_procesoregistrousuario'),
    ]

    operations = [
            migrations.RenameField(
        model_name="procesoregistrousuario",
        old_name="cedula_declarada",
        new_name="numero_documento_declarado",
    ),
    migrations.RenameField(
        model_name="procesoregistrousuario",
        old_name="cedula_verificada",
        new_name="numero_documento_verificado",
    ),
    ]
