# Generated by Django 5.2.17 on 2026-09-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0003_archivo_medico'),
        ('users', '0007_renombrar_campos_documento'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "DROP INDEX `users_proce_cedula__025474_idx` ON `users_procesoregistrousuario`;",
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name="procesoregistrousuario",
                    name="users_proce_cedula__025474_idx",
                )
            ],
        ),
        migrations.AddField(
            model_name='procesoregistrousuario',
            name='documento_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='procesoregistrousuario',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('PASAPORTE', 'Pasaporte'), ('RC', 'Registro civil')], default='CC', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procesoregistrousuario',
            name='numero_documento_declarado',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='procesoregistrousuario',
            name='numero_documento_verificado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='procesoregistrousuario',
            index=models.Index(fields=['tipo_documento', 'numero_documento_declarado', 'estado'], name='users_proce_tipo_do_c9fe76_idx'),
        ),
    ]
