# Generated by Django 5.2.17 on 2026-09-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_procesoregistrousuario_users_proce_cedula__025474_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('PASAPORTE', 'Pasaporte'), ('RC', 'Registro civil')], default='CC', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
