# Generated by Django 5.2.17 on 2026-09-29 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0003_archivo_medico'),
        ('users', '0009_usuario_tipo_documento_alter_usuario_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoregistrousuario',
            name='documento_reverso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_registro_usuario_reverso', to='storage_app.archivo'),
        ),
        migrations.AddField(
            model_name='procesoregistrousuario',
            name='documento_reverso_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
