# Generated by Django 5.2.17 on 2026-10-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_procesoregistrousuario_documento_reverso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesoregistrousuario',
            name='contraseña_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='procesoregistrousuario',
            name='correo',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='procesoregistrousuario',
            name='estatura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesoregistrousuario',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesoregistrousuario',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
