# Generated by Django 5.2.17 on 2026-10-08 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_procesoregistrousuario_contraseña_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('resuelto', 'Resuelto'), ('inactivo', 'Inactivo')], default='vigente', max_length=10)),
                ('es_permanente', models.BooleanField(default=False)),
                ('dosis', models.CharField(blank=True, max_length=80)),
                ('frecuencia', models.CharField(blank=True, max_length=100)),
                ('via_administracion', models.CharField(blank=True, max_length=60)),
                ('reaccion', models.CharField(blank=True, max_length=250)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_salud', to='users.usuario')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.tipoinfouser')),
            ],
            options={
                'ordering': ['id_tipo__nombre', 'nombre'],
                'indexes': [models.Index(fields=['id_usuario', 'id_tipo'], name='users_infou_id_usua_763487_idx')],
            },
        ),
    ]
