# Generated by Django 5.2.17 on 2026-10-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_tipoinfouser_infouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoregistrousuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('OTRO', 'Otro'), ('PREFIERO_NO_DECIR', 'Prefiero no decir')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='procesoregistrousuario',
            name='tipo_sangre',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('OTRO', 'Otro'), ('PREFIERO_NO_DECIR', 'Prefiero no decir')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_sangre',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
    ]
