# Generated by Django 5.2.17 on 2026-10-10 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_ciudad_api_id_departamento_api_id'),
        ('medicos', '0014_medico_correo_verificado_en_and_more'),
        ('storage_app', '0003_archivo_medico'),
        ('users', '0013_procesoregistrousuario_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoregistrousuario',
            name='ciudad_profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.ciudad'),
        ),
        migrations.AddField(
            model_name='procesoregistrousuario',
            name='direccion_profesional',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='procesoregistrousuario',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicos.especialidad'),
        ),
        migrations.AddField(
            model_name='procesoregistrousuario',
            name='hoja_vida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procesos_registro_medico', to='storage_app.archivo'),
        ),
        migrations.AddField(
            model_name='procesoregistrousuario',
            name='medico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proceso_registro', to='medicos.medico'),
        ),
        migrations.AddField(
            model_name='procesoregistrousuario',
            name='tipo_registro',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('medico', 'Médico')], default='paciente', max_length=10),
        ),
    ]
